### ISSUE TITLE
Preload dotenv

### ISSUE THREAD

**Issue by rviktor87** [noroon/kanban-backend#1]
https://github.com/noroon/kanban-backend/blob/ebcaaeeeb27a99ba29e2aef3e8767c9caff0bc4c/src/database/config.ts#L1-L4

You could preload dotenv in package.json instead of using it in the code: https://www.npmjs.com/package/dotenv#preload 
That can make the app a little bit faster

**Comment by noroon** [comment]
That's cool! Thanks! :dizzy:
